spring.application.name=user-service
spring.data.mongodb.uri=mongodb://localhost:27017/userdb
spring.cloud.discovery.enabled=true
server.port=8090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/user/v3/api-docs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/stage-shipping-realm
spring.web.resources.static-locations=classpath:/static/,classpath:/public/
spring.mvc.static-path-pattern=/static/**
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.security=DEBUG