spring.application.name=user-service
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.uri=mongodb://localhost:27017/userdb
spring.cloud.discovery.enabled=true
server.port=8084
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/user/v3/api-docs
# Keycloak (OAuth2 client config)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/test

# Keycloak Admin Client (used internally in services)
keycloak.realm=test
keycloak.auth-server-url=http://localhost:8080
keycloak.resource=springid
keycloak.credentials.secret=qOhZuzYYLpPPRhGpAcvQkDfGtJCw9pew

# Admin user credentials to manage Keycloak via API
keycloak.username=admin
keycloak.password=admin

file.upload-dir=uploads/
logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# === Configuration du client OAuth2 pour Keycloak ===

# Client OAuth2 du user-service (le client qui identifie user-service)
spring.security.oauth2.client.registration.springid.client-id=springid
spring.security.oauth2.client.registration.springid.client-secret=qOhZuzYYLpPPRhGpAcvQkDfGtJCw9pew
spring.security.oauth2.client.registration.springid.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.springid.scope=openid
spring.security.oauth2.client.provider.springid.token-uri=http://localhost:8080/realms/test/protocol/openid-connect/token

# Client OAuth2 pour appeler product-service
spring.security.oauth2.client.registration.product-service.client-id=product-service
spring.security.oauth2.client.registration.product-service.client-secret=vPoGwh673NQWNS7xvzC6v7JBPWR7XPUe
spring.security.oauth2.client.registration.product-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.product-service.scope=openid
spring.security.oauth2.client.provider.product-service.token-uri=http://localhost:8080/realms/test/protocol/openid-connect/token
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG