pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK23'
    }

    environment {
        SONAR_SERVER = 'sonar-server' // SonarQube server name in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: 'refs/heads/amen-React']],
                    userRemoteConfigs: [[url: 'https://github.com/AM3NN/shipping-application.git']],
                    extensions: [[$class: 'CloneOption', noTags: false, shallow: false, depth: 0]]
                ])
            }
        }

        stage('Build & Test All Services') {
            parallel {
                stage('Order Service') {
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            dir('backend/order-service') {
                                bat "mvn clean verify"
                            }
                        }
                    }
                    post {
                        always {
                            catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                                junit 'backend/order-service/target/surefire-reports/*.xml'
                                jacoco execPattern: '**/target/jacoco.exec',
                                       classPattern: '**/target/classes',
                                       sourcePattern: '**/src/main/java'
                            }
                        }
                    }
                }

                stage('Shipping Service') {
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            dir('backend/shipping-service') {
                                bat "mvn clean verify"
                            }
                        }
                    }
                    post {
                        always {
                            catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                                junit 'backend/shipping-service/target/surefire-reports/*.xml'
                                jacoco execPattern: '**/target/jacoco.exec',
                                       classPattern: '**/target/classes',
                                       sourcePattern: '**/src/main/java'
                            }
                        }
                    }
                }

                stage('Billing Service') {
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            dir('backend/billing-service') {
                                bat "mvn clean verify"
                            }
                        }
                    }
                    post {
                        always {
                            catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                                junit 'backend/billing-service/target/surefire-reports/*.xml'
                                jacoco execPattern: '**/target/jacoco.exec',
                                       classPattern: '**/target/classes',
                                       sourcePattern: '**/src/main/java'
                            }
                        }
                    }
                }
            }
        }

       stage('SonarQube Analysis') {
           steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                   withSonarQubeEnv("${env.SONAR_SERVER}") {
                       bat """
                           mvn sonar:sonar ^
                           -Dsonar.projectKey=order-service ^
                           -Dsonar.host.url=http://localhost:9000 ^
                           -Dsonar.login=sqa_1909642f8c661892915ded4761428df7f24c0e75
                       """
                   }
               }
           }
       }

        stage('Quality Gate') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    timeout(time: 5, unit: 'MINUTES') {
                        waitForQualityGate abortPipeline: true
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished. Check test reports and SonarQube results."
        }
    }
}
