spring.application.name=order-service
spring.data.mongodb.uri=mongodb://localhost:27017/Order_db
spring.cloud.discovery.enabled=true
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/orders/v3/api-docs
# Adresse du serveur Kafka
# Serveur Kafka
# Kafka Consumer Configuration
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=tn.epac.orderservice.Entities
spring.kafka.bootstrap-servers=localhost:9092

# Disable Docker Compose and OpenAI if not needed
spring.docker.compose.enabled=false

# ? Sécurité JWT Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/test
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=llama3:latest
logging.level.org.springframework.web=DEBUG
#spring.ai.vertex.ai.gemini.projectId=food-9i16xt
#spring.ai.vertex.ai.gemini.credentialsUri=classpath:keys/food-9i16xt-568e80caff16.json
#spring.ai.vertex.ai.gemini.location=europe-west3
#spring.ai.vertex.ai.gemini.chat.model=gemini-1.5-pro
spring.autoconfigure.exclude=org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration,org.springframework.ai.autoconfigure.vertexai.gemini.VertexAiGeminiAutoConfiguration
resilience4j.ratelimiter.instances.openai.limit-for-period=5
resilience4j.ratelimiter.instances.openai.limit-refresh-period=1s
resilience4j.ratelimiter.instances.openai.timeout-duration=0
