spring.application.name=shipping-service
spring.data.mongodb.uri=mongodb://localhost:27017/shippingdb
spring.cloud.discovery.enabled=true
server.port=8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
spring.data.rest.base-path=/api
fedex.api.token=l731d83c216d374d82a01e71314518a07f
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/stage-shipping-realm
management.endpoints.web.exposure.include=health,metrics
management.endpoints.web.exposure.exclude=*
keycloak.token.url=http://localhost:8080/realms/stage-shipping-realm/protocol/openid-connect/token
keycloak.client.id=order-service
keycloak.client.secret=bLULFbybrxFOppJdRa1P0y1xVh7FHrf5