spring.application.name=billing-service
spring.data.mongodb.uri=mongodb://localhost:27017/billingdb
spring.cloud.discovery.enabled=true
server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
spring.data.rest.base-path=/api
management.endpoints.web.exposure.exclude=*
order.service.url=http://localhost:8081
spring.mail.host=smtp.gmail.com
spring.mail.port=587    
spring.mail.username=laouiniamen1211@gmail.com
spring.mail.password=xagm vcyf xrcg jvkz
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true