spring.application.name=billing-service
spring.data.mongodb.uri=mongodb://localhost:27017/billing_db
spring.cloud.discovery.enabled=true
server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/billings/v3/api-docs
# Adresse du serveur Kafka
# Serveur Kafka
# Kafka Consumer Configuration


# Disable Docker Compose and OpenAI if not needed
spring.docker.compose.enabled=false

# ? Sécurité JWT Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/test
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=llama3:latest
logging.level.org.springframework.web=DEBUG
#spring.ai.vertex.ai.gemini.projectId=food-9i16xt
#spring.ai.vertex.ai.gemini.credentialsUri=classpath:keys/food-9i16xt-568e80caff16.json
#spring.ai.vertex.ai.gemini.location=europe-west3
#spring.ai.vertex.ai.gemini.chat.model=gemini-1.5-pro
spring.autoconfigure.exclude=org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration,org.springframework.ai.autoconfigure.vertexai.gemini.VertexAiGeminiAutoConfiguration
resilience4j.ratelimiter.instances.openai.limit-for-period=5
resilience4j.ratelimiter.instances.openai.limit-refresh-period=1s
resilience4j.ratelimiter.instances.openai.timeout-duration=0
# Client OAuth2 pour appeler order-service
spring.security.oauth2.client.registration.order-service.client-id=order-service
spring.security.oauth2.client.registration.order-service.client-secret=dfQX73Ip8gds36feu7R0luoXuySub5pC
spring.security.oauth2.client.registration.order-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.order-service.scope=openid
spring.security.oauth2.client.provider.order-service.token-uri=http://localhost:8080/realms/test/protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/test/protocol/openid-connect/certs
# Client OAuth2 du user-service (le client qui identifie user-service)
spring.security.oauth2.client.registration.user-service.client-id=user-service
spring.security.oauth2.client.registration.user-service.client-secret=ECHl5X4YxO23t4RHcmw9MxvSBR1zER9p
spring.security.oauth2.client.registration.user-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.user-service.scope=openid
spring.security.oauth2.client.provider.user-service.token-uri=http://localhost:8080/realms/test/protocol/openid-connect/token

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=epac.internship@gmail.com
spring.mail.password=ycxwwcyilxuboatk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.protocol=smtp

