server.port=8082
spring.application.name=product-service
spring.data.mongodb.uri=mongodb://localhost:27017/productdb
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/products/v3/api-docs
# ? Sécurité JWT Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/test
logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.docker.compose.enabled=false
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.http=TRACE
logging.level.tn.epac.product=TRACE
# Niveau de log global
logging.level.root=INFO

# Niveau de log spécifique à votre package
logging.level.tn.epac.productservice.Controllers=DEBUG

# (Optionnel) Formatage de la sortie
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
spring.web.resources.static-locations=file:uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# Kafka Producer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer