pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK23'
    }

    environment {
        MAVEN_OPTS = '-Dmaven.test.failure.ignore=false'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'amen-React', url: 'https://github.com/AM3NN/shipping-application.git'
            }
        }

        stage('Build Order Service') {
            steps {
                dir('backend/order-service') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('backend/order-service') {
                    bat 'mvn test'
                }
            }
        }
        stage('Generate Coverage Report') {
            steps {
                dir('backend/order-service') {
                    bat 'mvn verify'
                }
            }
        }


        stage('Publish Test Results') {
            steps {
                junit 'backend/order-service/target/surefire-reports/*.xml'
            }
        }
        stage('Publish JaCoCo Report') {
            steps {
                jacoco execPattern: '**/target/jacoco.exec', classPattern: '**/target/classes', sourcePattern: '**/src/main/java', exclusionPattern: '**/target/test-classes'
            }
        }

    }
}
