pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK23'
    }

    environment {
        MAVEN_OPTS = '-Dmaven.test.failure.ignore=false'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'amen-React', url: 'https://github.com/AM3NN/shipping-application.git'
            }
        }

        stage('Build Order Service') {
            steps {
                dir('backend/order-service') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('backend/order-service') {
                    sh 'mvn test'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'backend/order-service/target/surefire-reports/*.xml'
            }
        }
    }
}
