pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK23'
    }

    environment {
        MAVEN_OPTS = '-Dmaven.test.failure.ignore=false'
        SONAR_HOST_URL = 'http://localhost:9000'  // update if needed
        SONAR_LOGIN = credentials('sonar-token-id') // Jenkins credential ID for Sonar token
        SONAR_PROJECT_KEY = 'order-service'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: 'refs/heads/amen-React']],
                    userRemoteConfigs: [[url: 'https://github.com/AM3NN/shipping-application.git']],
                    extensions: [[$class: 'CloneOption', noTags: false, shallow: false, depth: 0]]
                ])
            }
        }

        stage('Build Order Service') {
            steps {
                dir('backend/order-service') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('backend/order-service') {
                    bat 'mvn test'
                }
            }
        }

        stage('Generate Coverage Report') {
            steps {
                dir('backend/order-service') {
                    bat 'mvn verify'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('backend/order-service') {
                    bat """
                    mvn org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar ^
                      -Dsonar.projectKey=${env.SONAR_PROJECT_KEY} ^
                      -Dsonar.host.url=${env.SONAR_HOST_URL} ^
                      -Dsonar.login=${env.SONAR_LOGIN}
                    """
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'backend/order-service/target/surefire-reports/*.xml'
            }
        }

        stage('Publish JaCoCo Report') {
            steps {
                jacoco execPattern: '**/target/jacoco.exec', classPattern: '**/target/classes', sourcePattern: '**/src/main/java', exclusionPattern: '**/target/test-classes'
            }
        }
    }
}
