sonar.projectKey=order-service
sonar.projectName=Order Service
sonar.projectVersion=1.0

# Source settings
sonar.sources=src
sonar.java.binaries=target


# SonarQube server
sonar.host.url=http://localhost:9000
sonar.login=sqp_1421b5b30a3d2fbaf664cd9bde97d1dc674b62e1
